# Generated by Django 4.1.1 on 2022-09-29 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Nurse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_appoint', models.BooleanField(default=False)),
                ('appoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Nurse.nurse')),
            ],
        ),
    ]
